export const attackDetails = [
  {
    attackId: 'a0',
    displayName: 'éternuement',// affichage et les logs
	attackTarget: ['enemy'],
	attackDescription: 'L\’entité éternue. Rien d’inattendu, sinon peut-être l\’insignifiance de son action.',
	attackRange: ['melee'],
	attacknature: ['physicalDamage'],
    functionName: 'sneeze', // 
    preparationTime: 1000,
    executionTime: 1000,
    recoveryTime: 1000,
    cooldown: 1000,
	effets:	['none'],
	attackAsset: '/media/assets/spells/sneeze-spell-art.jpg',
	castingAsset: '../../media/assets/effects/1.gif',
  },  {
    attackId: 'a1',
    displayName: 'Auto-attaque',
	attackTarget: ['enemy'],
	attacknature: ['physicalDamage'],
	attackRange: ['melee'],
	attackDescription: 'Attaque de base de toute entité capable de se défendre un minimum. Inflige {$totalDamage} à la cible.',
    functionName: 'autoAttack',
    preparationTime: 500,
    executionTime: 500,
    recoveryTime: 500,
    cooldown: 500, 
	effets:	['none'],
	attackAsset: '/media/assets/spells/auto-attack-spell-art.jpg',
	physicalRatio: 0.8, // 80 % des dégâts viennent de physicalDamage
	magicalRatio: 0,
	castingAsset: '../../media/assets/effects/1.gif',
  },{
    attackId: 'a2',
    displayName: 'Quick Attack',
	attackTarget: ['enemy'],
	attackRange: ['melee'],
	attacknature: ['physicalDamage'],
	attackDescription: 'Frappe légére, qui privilégie la rapidité aux dégats effectués à la cible.',
    functionName: 'quickAttack',
    preparationTime: 500,
    executionTime: 500,
    recoveryTime: 500,
    cooldown: 3000, 
	effets:	['none'],
	attackAsset: '/media/assets/spells/quick-attack-spell-art.jpg',
  }, {
	attackId: 'a3',
    displayName: 'Asticoterie', 
	attackTarget: ['enemy'],
	attackRange: ['melee'],
	attacknature: ['physicalDamage'],
	attackDescription: 'Attaque propre aux entités grouillantes. Les données récoltées sont trop faibles pour être plus exposées. Ou peut être n\'y a t\'il pas vraiment d\'interet de le faire...',
    functionName: 'asticoterie', 
    preparationTime: 1000,
    executionTime: 10000,
    recoveryTime: 1000,
    cooldown: 20000, 
	effets:	['none'],
	attackAsset: '/media/assets/spells/asticoterie-spell-art.jpg',
   },{
	attackId: 'a4',
    displayName: 'Venin', 
	attackTarget: ['enemy'],
	attackRange: ['melee'],
	attacknature: ['magicalDamage'],
	attackDescription: 'Empoisonne la cible. Inflige [{baseDamage} + ({physicalRatio}*{physicalDamage}) + ({magicalRatio}*{magicalDamage})] puis DOT : [{effectDot}*({effectMagicalRatio}+{effectPhysicalRatio})] sur {effectDuration} secondes.{effectDot}+({effectDot}*{effectMagicalRatio}+{effectPhysicalRatio}). {totalPhysicalDamage} + {totalMagicalDamage} = {totalExecutionDamage}',
    functionName: 'venin', 
    preparationTime: 3000,
    executionTime: 2000,
    recoveryTime: 2000,
    cooldown: 6000,
	effets:	['poison'],
	attackAsset: '../media/assets/spells/venin-spell-art.jpg',
	physicalRatio: 0, // 80 % des dégâts viennent de physicalDamage
	magicalRatio: 1.2, // 20 % des dégâts viennent de magicalDamage
	castingAsset: '../../media/assets/effects/1.gif',
  },{
	attackId: 'a5',
    displayName: 'Incinération', 
	attackTarget: ['enemy'],
	attackRange: ['range'],
	attacknature: ['magicalDamage'],
	attackDescription: 'Incinére la cible, lui infligeant des dégats à l\'impact ainsi que brûlure. La brulure se stacke 5 fois, infligeant des dégats supplémentaires à chaque stacke, et réinitialisant sa durée.',
    functionName: 'incineration', 
	attackAP: 10,
    preparationTime: 3000,
    executionTime: 1000,
    recoveryTime: 2000,
    cooldown: 6000, 
	effets:	['brulure'],
	attackAsset: '../media/assets/spells/brulure-spell-art.jpg',
	castingAsset: '../../media/assets/effects/magic-circle.png',
  },{
	attackId: 'a6',
    displayName: 'Soin', 
	attackTarget: ['ally'],
	attacknature: ['magicalDamage'],
	attackRange: ['range'],
	attackDescription: 'Restaure des HP à la cible.',
    functionName: 'soin', 
    preparationTime: 3000,
    executionTime: 1000,
    recoveryTime: 2000,
    cooldown: 6000, 
	effets:	['heal'],
	attackAsset: '../media/assets/spells/heal-spell-art.jpg',
  },{
	attackId: 'a7',
    displayName: 'Résurrection', 
	attackTarget: ['ally'],
	attackRange: ['range'],
	deadTarget: ['yes'],
	attacknature: ['magicalDamage'],
	attackDescription: 'Ressusciter une cible alliée tombée au combat.',
    functionName: 'resurrection', 
    preparationTime: 3000,
    executionTime: 4000,
    recoveryTime: 2000,
    cooldown: 6000, 
	effets:	['rez'],
	attackAsset: '../media/assets/spells/resurrection-spell-art.jpg',
 },{
	attackId: 'a8',
    displayName: 'Lancé de jarret', 
	attacknature: ['physicalDamage'],
	attackTarget: ['hexa'],
	attackRange: ['range'],
	attackDescription: 'Envoie un jarret juteux sur une case qui soigne toute entité positionnée dessus. Attention cependant à ce qu\'il soit bien frais...',
    functionName: 'lancedejarret', 
    preparationTime: 3000,
    executionTime: 2000,
    recoveryTime: 4000,
    cooldown: 6000, 
	effets:	['summonJarret'],
	attackAsset: '../media/assets/spells/lance-de-jarret-spell-art.jpg',
	 },{
	attackId: 'a9',
    displayName: 'Profanation', 
	attackTarget: ['enemy'],
	attackRange: ['range'],
	attacknature: ['magicalDamage'],
	deadTarget: ['yes'],
	attackDescription: 'Profanne le cadavre d\'un ennemi pour ramener à la vie une abomination de chair.',
    functionName: 'profanation', 
    preparationTime: 3000,
    executionTime: 2000,
    recoveryTime: 4000,
    cooldown: 6000, 
	effets:	['summonProfanation'],
	attackAsset: '../media/assets/spells/profanation-spell-art.jpg',
	 },{
	attackId: 'a10',
    displayName: 'Dead-shot', 
	attackTarget: ['enemy'],
	attacknature: ['physicalDamage'],
	attackRange: ['range'],
	attackDescription: 'Décoche une flêche surpuissante faisant d\'énorme dégats à la cible. Attaque très longue à charger.',
    functionName: 'deadshot', 
    preparationTime: 6000,
    executionTime: 500,
    recoveryTime: 1000,
    cooldown: 6000, 
	effets:	['deadshotfx'],
	attackAsset: '../media/assets/spells/deadshot-art.jpg',
	}, {
	attackId: 'a11',
    displayName: 'Morsure goulue',
    attackTarget: ['enemy'],
	attackRange: ['melee'],
    attackDescription: 'Mord goulûment l\'adversaire, lui infligeant {$totalDamage}, et soignant l\'attaquant pour un pourcentage des dégats infligés.',
    functionName: 'morsure-goulue',
    preparationTime: 10000,
    executionTime: 3000,
    recoveryTime: 1000,
    cooldown: 500,
    effets: ['none'],
    selfEffects: ['lifesteal'], 
    attackAsset: '../media/assets/spells/morsure-goulue.jpg',
	castingAsset: '../../media/assets/effects/1.gif',
	attacknature: ['hybridalDamage'],
	physicalRatio: 0.2, 
	magicalRatio: 0.3,
	
	 },{
	attackId: 'a12',
    displayName: 'Boulasse de feu', 
	attackTarget: ['enemy'],
	attackRange: ['range'],
	attackDescription: 'Projette une boule de feu sur l\'ennemi qui inflige {$totalDamage} sur la cible.',
    functionName: 'boulassefeu', 
	attacknature: ['magicalDamage'],
    preparationTime: 2000,
    executionTime: 10000,
    recoveryTime: 3000,
    cooldown: 7000, 
	effets:	['none'],
	attackAsset: '../media/assets/spells/flamme-spell-art.jpg',
	castingAsset: '../../media/assets/effects/magic-circle.png',
	physicalRatio: 0, 
	magicalRatio: 0.5,
	
	},{
	attackId: 'a13',
    displayName: 'Tir p r', 
	attackTarget: ['enemy'],
	attackRange: ['range'],
	attackDescription: 'Tire un projectil en direction de la cible.',
    functionName: 'shot-p-r', 
	attacknature: ['physicalDamage'],
    preparationTime: 1000,
    executionTime: 10000,
    recoveryTime: 1000,
    cooldown: 2000, 
	effets:	['none'],
	attackAsset: '../media/assets/spells/tir.jpg',
	castingAsset: '../../media/assets/effects/1.gif',
	physicalRatio: 0.5, 
	magicalRatio: 0.5,
		},{
	attackId: 'a13',
    displayName: 'Tir cp', 
	attackTarget: ['enemy'],
	attackRange: ['melee'],
	attackDescription: 'Tire un projectil en direction de la cible.',
    functionName: 'shot-p-c', 
	attacknature: ['physicalDamage'],
    preparationTime: 1000,
    executionTime: 10000,
    recoveryTime: 1000,
    cooldown: 2000, 
	effets:	['none'],
	attackAsset: '../media/assets/spells/tir.jpg',
	castingAsset: '../../media/assets/effects/1.gif',
	physicalRatio: 0.5, 
	magicalRatio: 0.5,
			},{
	attackId: 'a13',
    displayName: 'Tir m-c', 
	attackTarget: ['enemy'],
	attackRange: ['melee'],
	attackDescription: 'Tire un projectil en direction de la cible.',
    functionName: 'shot-m-c', 
	attacknature: ['magicalDamage'],
    preparationTime: 1000,
    executionTime: 10000,
    recoveryTime: 1000,
    cooldown: 2000, 
	effets:	['none'],
	attackAsset: '../media/assets/spells/tir.jpg',
	castingAsset: '../../media/assets/effects/1.gif',
	physicalRatio: 0.5, 
	magicalRatio: 0.5,
			},{
	attackId: 'a13',
    displayName: 'Tir range magi', 
	attackTarget: ['enemy'],
	attackRange: ['range'],
	attackDescription: 'Tire un projectil en direction de la cible.',
    functionName: 'shot-m-r', 
	attacknature: ['magicalDamage'],
    preparationTime: 1000,
    executionTime: 10000,
    recoveryTime: 1000,
    cooldown: 2000, 
	effets:	['none'],
	attackAsset: '../media/assets/spells/tir.jpg',
	castingAsset: '../../media/assets/effects/1.gif',
	physicalRatio: 0.5, 
	magicalRatio: 0.5,
	},{
	attackId: 'a13',
    displayName: 'Tir', 
	attackTarget: ['enemy'],
	attackRange: ['range'],
	attackDescription: 'Tire un projectil en direction de la cible.',
    functionName: 'shot-h-r', 
	attacknature: ['hybridalDamage'],
    preparationTime: 1000,
    executionTime: 10000,
    recoveryTime: 1000,
    cooldown: 2000, 
	effets:	['none'],
	attackAsset: '../media/assets/spells/tir.jpg',
	castingAsset: '../../media/assets/effects/1.gif',
	physicalRatio: 0.5, 
	magicalRatio: 0.5,
		},{
	attackId: 'a13',
    displayName: 'Tir', 
	attackTarget: ['enemy'],
	attackRange: ['melee'],
	attackDescription: 'Tire un projectil en direction de la cible.',
    functionName: 'shot-h-c', 
	attacknature: ['hybridalDamage'],
    preparationTime: 1000,
    executionTime: 3000,
    recoveryTime: 1000,
    cooldown: 2000, 
	effets:	['none'],
	attackAsset: '../media/assets/spells/tir.jpg',
	castingAsset: '../../media/assets/effects/1.gif',
	physicalRatio: 0.5, 
	magicalRatio: 0.5,
	
	},{
	attackId: 'a14',
    displayName: 'Tir', 
	attackTarget: ['enemy'],
	attackRange: ['range'],
	attackDescription: 'Tire un projectil en direction de la cible.',
    functionName: 'shot-b-r', 
	attacknature: ['piercingDamage'],
    preparationTime: 1000,
    executionTime: 3000,
    recoveryTime: 1000,
    cooldown: 2000, 
	effets:	['none'],
	attackAsset: '../media/assets/spells/tir.jpg',
	castingAsset: '../../media/assets/effects/1.gif',
	physicalRatio: 0.5, 
	magicalRatio: 0.5,
	
	},  
];