// targetStatut: ' new-target, active-target, last-target',
export const entitesNest = [
{
		serial: 1,
		id: 2,
		power: 5,
        name: 'Mouche asticoteuse',
		class: 'mouche-asticoteuse',
		type: 'sbire',
		lore: 'Créature boursoufflée et agaçante.',
		description:'Une Entité teigneuse qui provoque des dégats importants sur la durée.',
		sprite:"../../media/sprites/mouche-asticoteuse.png",
		portrait:"../../media/portrait/mouche-asticoteuse.jpg",
		DeadSprite: null, 
        attacks: ['autoAttack'],
		stuff:[],
			baseStats: {
			strength:1,
			agility:1,
			intelligence:1,
			will:20,
			HP: 850000,
			dayHpRegen:1,
			indestructibility: 80,
			extraLife: 1,
			speed: 500,
			piercingDamage: 2,
			physicalDamage: 30,
            magicalDamage: 6,
			physicalResistance:80,
			magicalResistance:50,
			vitality: 8,
			velocity: 5,
			dodge: 20,
			evade: 100,
			precision: 80,
			charge:1,
			physicalPen: 80,
			magicalPen: 2,
			bloodFury: 20,
			ambidextry:30,
			robustness:150,
			criticalChance: 50,
        },
		side: '',
		position: '',
		role:['tank'],
		classe:[],
},{
		serial: 2,
		id: 1,
		power: 4,
        name: 'Porc hybride cac in',
		class: 'porc-bas-fond',
		type: 'sbire',
		lore: 'Ne vous laissez pas tromper par l\'apparence grotesque d\'un Porc des Bas-Fonds. Avec sa silhouette grassouillette et son air un peu sale, ces Entités cachent bien des qualités.',
		description:'Une Entité teigneuse qui provoque des dégats importants sur la durée.',
		sprite:"../../media/sprites/porc-des-bas-fond.png",
		portrait:"../../media/portrait/porc-des-bas-fond.jpg",
		DeadSprite: null, 
        attacks: ['shot-h-c'],
		stuff:[],
		baseStats: {
			strength:1,
			agility:3,
			dayHpRegen:3,
			intelligence:5,
			will:25,
			HP: 56,
			extraLife: {
                    "current": 1,
                    "max": 10
                },
				fadedLife: 1,
				eternalLife: 1,
			speed: 500,
			piercingDamage: 4,
			physicalDamage: 10,
            magicalDamage: 10,
			physicalResistance: 5,
			magicalResistance: 5,
			vitality: 58,
			velocity: 80,
			dodge: 2,
			precision: 5,
			charge:2,
			robustness: 2,
			indestructibility: 50,
			resilience: 50,
			hypercognition:0,
			ambidextry:50,
			transcendence:1,
        },
		side: '',
		position: '',
		role:['mage'],
		classe:[],
},{
		serial: 3,
		id: 1,
		power: 4,
        name: 'Porc hybride cac no ind',
		class: 'porc-bas-fond',
		type: 'sbire',
		lore: 'Ne vous laissez pas tromper par l\'apparence grotesque d\'un Porc des Bas-Fonds. Avec sa silhouette grassouillette et son air un peu sale, ces Entités cachent bien des qualités.',
		description:'Une Entité teigneuse qui provoque des dégats importants sur la durée.',
		sprite:"../../media/sprites/porc-des-bas-fond.png",
		portrait:"../../media/portrait/porc-des-bas-fond.jpg",
		DeadSprite: null, 
        attacks: ['shot-h-c'],
		stuff:[],
		baseStats: {
			strength:1,
			agility:3,
			dayHpRegen:3,
			intelligence:5,
			will:25,
			HP: 56,
			extraLife: {
                    "current": 1,
                    "max": 10
                },
				fadedLife: 1,
				eternalLife: 1,
			speed: 500,
			piercingDamage: 4,
			physicalDamage: 10,
            magicalDamage: 10,
			physicalResistance: 5,
			magicalResistance: 5,
			vitality: 58,
			velocity: 80,
			dodge: 2,
			precision: 5,
			charge:2,
			robustness: 2,
			indestructibility: 0,
			resilience: 50,
			hypercognition:0,
			ambidextry:50,
			transcendence:1,
        },
		side: '',
		position: '',
		role:['mage'],
		classe:[],
},{
		serial: 4,
		id: 1,
		power: 4,
        name: 'Porc hybride range',
		class: 'porc-bas-fond',
		type: 'sbire',
		lore: 'Ne vous laissez pas tromper par l\'apparence grotesque d\'un Porc des Bas-Fonds. Avec sa silhouette grassouillette et son air un peu sale, ces Entités cachent bien des qualités.',
		description:'Une Entité teigneuse qui provoque des dégats importants sur la durée.',
		sprite:"../../media/sprites/porc-des-bas-fond.png",
		portrait:"../../media/portrait/porc-des-bas-fond.jpg",
		DeadSprite: null, 
        attacks: ['shot-h-r'],
		stuff:[],
		baseStats: {
			strength:1,
			agility:3,
			dayHpRegen:3,
			intelligence:5,
			will:25,
			HP: 56,
			extraLife: {
                    "current": 1,
                    "max": 10
                },
				fadedLife: 1,
				eternalLife: 1,
			speed: 500,
			piercingDamage: 4,
			physicalDamage: 10,
            magicalDamage: 10,
			physicalResistance: 5,
			magicalResistance: 5,
			vitality: 58,
			velocity: 80,
			dodge: 2,
			precision: 5,
			charge:2,
			robustness: 2,
			indestructibility: 0,
			resilience: 50,
			hypercognition:0,
			ambidextry:50,
			transcendence:1,
        },
		side: '',
		position: '',
		role:['mage'],
		classe:[],
},{
		serial: 5,
		id: 1,
		power: 4,
        name: 'Porc magi range',
		class: 'porc-bas-fond',
		type: 'sbire',
		lore: 'Ne vous laissez pas tromper par l\'apparence grotesque d\'un Porc des Bas-Fonds. Avec sa silhouette grassouillette et son air un peu sale, ces Entités cachent bien des qualités.',
		description:'Une Entité teigneuse qui provoque des dégats importants sur la durée.',
		sprite:"../../media/sprites/porc-des-bas-fond.png",
		portrait:"../../media/portrait/porc-des-bas-fond.jpg",
		DeadSprite: null, 
        attacks: ['shot-m-r'],
		stuff:[],
		baseStats: {
			strength:1,
			agility:3,
			dayHpRegen:3,
			intelligence:5,
			will:25,
			HP: 56,
			// extraLife: {
                    // "current": 1,
                    // "max": 10
                // },
				// fadedLife: 1,
				// eternalLife: 1,
			speed: 500,
			piercingDamage: 4,
			physicalDamage: 10,
            magicalDamage: 10,
			physicalResistance: 5,
			magicalResistance: 5,
			vitality: 58,
			velocity: 80,
			dodge: 2,
			precision: 5,
			charge:2,
			robustness: 2,
			indestructibility: 10,
			resilience: 50,
			hypercognition:0,
			ambidextry:50,
			transcendence:1,
        },
		side: '',
		position: '',
		role:['mage'],
		classe:[],
},{
		serial: 6,
		id: 1,
		power: 4,
        name: 'Porc magi cac',
		class: 'porc-bas-fond',
		type: 'sbire',
		lore: 'Ne vous laissez pas tromper par l\'apparence grotesque d\'un Porc des Bas-Fonds. Avec sa silhouette grassouillette et son air un peu sale, ces Entités cachent bien des qualités.',
		description:'Une Entité teigneuse qui provoque des dégats importants sur la durée.',
		sprite:"../../media/sprites/porc-des-bas-fond.png",
		portrait:"../../media/portrait/porc-des-bas-fond.jpg",
		DeadSprite: null, 
        attacks: ['shot-m-c'],
		stuff:[],
		baseStats: {
			strength:1,
			agility:3,
			dayHpRegen:3,
			intelligence:5,
			will:25,
			HP: 56,
			// extraLife: {
                    // "current": 1,
                    // "max": 10
                // },
				// fadedLife: 1,
				// eternalLife: 1,
			speed: 500,
			piercingDamage: 4,
		physicalDamage: 10,
            magicalDamage: 10,
			physicalResistance: 5,
			magicalResistance: 5,
			vitality: 58,
			velocity: 80,
			dodge: 2,
			precision: 5,
			charge:2,
			robustness: 2,
			indestructibility: 0,
			resilience: 50,
			hypercognition:0,
			ambidextry:50,
			transcendence:1,
        },
		side: '',
		position: '',
		role:['mage'],
		classe:[],
},{
		serial: 7,
		id: 1,
		power: 4,
        name: 'Porc physic cac',
		class: 'porc-bas-fond',
		type: 'sbire',
		lore: 'Ne vous laissez pas tromper par l\'apparence grotesque d\'un Porc des Bas-Fonds. Avec sa silhouette grassouillette et son air un peu sale, ces Entités cachent bien des qualités.',
		description:'Une Entité teigneuse qui provoque des dégats importants sur la durée.',
		sprite:"../../media/sprites/porc-des-bas-fond.png",
		portrait:"../../media/portrait/porc-des-bas-fond.jpg",
		DeadSprite: null, 
        attacks: ['shot-p-c'],
		stuff:[],
		baseStats: {
			strength:1,
			agility:3,
			dayHpRegen:3,
			intelligence:5,
			will:25,
			HP: 56,
			// extraLife: {
                    // "current": 1,
                    // "max": 10
                // },
				// fadedLife: 1,
				// eternalLife: 1,
			speed: 500,
			piercingDamage: 4,
			physicalDamage: 10,
            magicalDamage: 10,
			physicalResistance: 5,
			magicalResistance: 5,
			vitality: 58,
			velocity: 80,
			dodge: 2,
			precision: 5,
			charge:2,
			robustness: 2,
			indestructibility: 0,
			resilience: 50,
			hypercognition:0,
			ambidextry:50,
			transcendence:1,
        },
		side: '',
		position: '',
		role:['mage'],
		classe:[],
},{
		serial: 8,
		id: 1,
		power: 4,
        name: 'Porc physic range',
		class: 'porc-bas-fond',
		type: 'sbire',
		lore: 'Ne vous laissez pas tromper par l\'apparence grotesque d\'un Porc des Bas-Fonds. Avec sa silhouette grassouillette et son air un peu sale, ces Entités cachent bien des qualités.',
		description:'Une Entité teigneuse qui provoque des dégats importants sur la durée.',
		sprite:"../../media/sprites/porc-des-bas-fond.png",
		portrait:"../../media/portrait/porc-des-bas-fond.jpg",
		DeadSprite: null, 
        attacks: ['shot-p-r'],
		stuff:[],
		baseStats: {
			strength:1,
			agility:3,
			dayHpRegen:3,
			intelligence:5,
			will:25,
			HP: 56,
			// extraLife: {
                    // "current": 1,
                    // "max": 10
                // },
				// fadedLife: 1,
				// eternalLife: 1,
			speed: 500,
			piercingDamage: 4,
			physicalDamage: 10,
            magicalDamage: 10,
			physicalResistance: 5,
			magicalResistance: 5,
			vitality: 58,
			velocity: 80,
			dodge: 2,
			precision: 5,
			charge:2,
			robustness: 2,
			indestructibility: 10,
			resilience: 50,
			hypercognition:0,
			ambidextry:50,
			transcendence:1,
        },
		side: '',
		position: '',
		role:['mage'],
		classe:[],
},{
		serial: 9,
		id: 3,
		power: 7,
        name: 'Jeune Salamandron',
		class: 'jeune-salamandron',
		type: 'sbire',
		lore: 'Ne vous laissez pas tromper par l\'apparence grotesque d\'un Porc des Bas-Fonds. Avec sa silhouette grassouillette et son air un peu sale, ces Entités cachent bien des qualités.',
		description:'Une Entité qui peut se régénérer en attaquant.',
		sprite:"../../media/sprites/jeune-salamandron.png",
		portrait:"../../media/portrait/jeune-salamandron.jpg",
		DeadSprite: null, 
        attacks: ['morsure-goulue'],
		stuff:[],
		baseStats: {
	strength:1,
	agility:3,
	intelligence:5,
	will:30,
	HP: 15,
	dayHpRegen:0,
	speed: 500,
	piercingDamage: 16,
	physicalDamage: 3,
    magicalDamage: 3,
	physicalResistance:5,
	magicalResistance:20,
	vitality: 5,
			velocity: 2,
			dodge: 1,
			precision: 5,
			charge: 0,
			bloodFury: 2,
			physicalPen: 1,
		magicalPen: 2,
		robustness: 3,
		indestructibility: 20,
		resilience: 2,
		hypercognition: 1,
		astrality: 2,
		transcendence: 50,
		extraLife: 1,
		haste: 2,
		equilibre: 1,
		mysticism: 1,
		ambidextry: 6,
		esoterism: 40,
		occultism: 1,
		movement: 2,
		criticalChance: 1,
		},
		side: '',
		position: '',
		role:['fantassin'],
		classe:[],
},{
		serial: 10,
		id: 15,
		power: 15,
		name: 'Torche Noire',
		class: 'torche-noire',
		type: 'sbire',
		lore: 'Ne vous laissez pas tromper par l\'apparence grotesque d\'un Porc des Bas-Fonds. Avec sa silhouette grassouillette et son air un peu sale, ces Entités cachent bien des qualités.',
		description:'Une Entité qui peut se régénérer en attaquant.',
		sprite:"../../media/sprites/torche-noire.png",
		portrait:"../../media/portrait/torche-noire.jpg",
		DeadSprite: null, 
        attacks: ['morsure-goulue'],
		stuff:[],
		baseStats: {
			strength:1,
			agility:3,
			intelligence:5,
			will:95,
			HP: 70,
			extraLife: 0,
			speed: 5000,
			piercingDamage: 16,
			physicalDamage: 20,
            magicalDamage: 35,
			physicalResistance:35,
			magicalResistance:20,
			vitality: 5,
			velocity: 2,
			dodge: 1,
			precision: 5,
			charge:4,
        },
		side: '',
		position: '',
		role:['mage'],
		classe:[],
},{
		serial: 11,
		id: 2544,
		power: 1,
        name: 'Grouille-Doigt',
		class: 'grouille-doigt',
		type: 'sbire',
		lore: 'Créature boursoufflée et agaçante.',
		description:'Une Entité teigneuse qui provoque des dégats importants sur la durée.',
		sprite:"../../media/sprites/grouille-doigt.png",
		portrait:"../../media/portrait/grouille-doigt.jpg",
		DeadSprite: null, 
        attacks: ['sneeze'],
		stuff:[],
			baseStats: {
			strength:1,
			agility:1,
			intelligence:1,
			will:10,
			HP: 300,
			speed: 500,
			fadedLife: 4,
			physicalDamage: 1,
            magicalDamage: 1,
			physicalResistance:1,
			magicalResistance:11,
			vitality: 1,
			velocity: 1,
			dodge: 5,
			haste:130,
        },
		side: '',
		position: '',
		role:['fantassin'],
		classe:[],
},{
		serial: 12,
		id: 57470, 
		power: 8,
         name: 'Escargot coulissant',
		class: 'escargot-coulissant',
		type: 'sbire',
		lore: 'Il coulisse. Lentement... Surement... Dégoulinant.',
		description:'Une entité venimeuse, capable de faire chuter vos points de vie à un rythme bien plus soutenu que ne le laisse présager le bestiau.',
		sprite:"../../media/sprites/escargot-coulissant.png",
		portrait:"../../media/portrait/escargot-coulissant.jpg",
		DeadSprite: null, 
        attacks: ['venin'],
		stuff:[],
			baseStats: {
			strength:1,
			agility:1,
			will:5,
			intelligence:1,
			HP: 850,
			speed: 500,
			magicalDamage: 6,
			vitality: 8,
			velocity: 5,
			dodge: 20,
			evade: 10,
			precision: 8,
			charge:1,
			magicalPen: 85,
			robustness:15,
			
        },
		side: '',
		position: '',
		role:['mage'],
		classe:[],
},{
		serial: 13,
		id: 1,
		power: 4,
        name: 'Porc brutal range',
		class: 'porc-bas-fond',
		type: 'sbire',
		lore: 'Ne vous laissez pas tromper par l\'apparence grotesque d\'un Porc des Bas-Fonds. Avec sa silhouette grassouillette et son air un peu sale, ces Entités cachent bien des qualités.',
		description:'Une Entité teigneuse qui provoque des dégats importants sur la durée.',
		sprite:"../../media/sprites/porc-des-bas-fond.png",
		portrait:"../../media/portrait/porc-des-bas-fond.jpg",
		DeadSprite: null, 
        attacks: ['shot-b-r'],
		stuff:[],
		baseStats: {
			strength:1,
			agility:3,
			dayHpRegen:3,
			intelligence:5,
			will:25,
			HP: 56,
			// extraLife: {
                    // "current": 1,
                    // "max": 10
                // },
				// fadedLife: 1,
				// eternalLife: 1,
			speed: 500,
			piercingDamage: 4,
			physicalDamage: 10,
            magicalDamage: 10,
			physicalResistance: 5,
			magicalResistance: 5,
			vitality: 58,
			velocity: 80,
			dodge: 2,
			precision: 5,
			charge:2,
			robustness: 2,
			indestructibility: 10,
			resilience: 50,
			hypercognition:0,
			ambidextry:50,
			transcendence:1,
        },
		side: '',
		position: '',
		role:['mage'],
		classe:[],
},


];



